const item = [
  {
    id: "001",
    name: "Contemporary Tripod Floor Lamp",
    company: "Homesake",
    price: {
      current_price: 1899,
      original_price: 11000,
      off_price: "(Rs.9101 OFF)",
    },
    rating: "4.3 ★ | 61",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/home_lamp.webp",
  },
  {
    id: "002",
    company: "SASHAA WORLD",
    name: "Self-Design Pure Cotton Runnner",
    price: {
      current_price: 986,
      original_price: 2990,
      off_price: "(67% OFF)",
    },
    rating: "4.4 ★ | 21",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/home_heart.webp",
  },
  {
    id: "003",
    name: "Kids Running Shoes",
    company: "Liberty",
    price: {
      current_price: 884,
      original_price: 1499,
      off_price: "(41% OFf)",
    },
    rating: "4.7 ★ | 49",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/shoes.webp",
  },
  {
    id: "004",
    name: "Rectangle Cake Mould",
    company: "ZEVORA",
    price: {
      current_price: 499,
      original_price: 1999,
      off_price: "(75% OFF)",
    },
    rating: "5 ★ | 6",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/bake_ware.webp",
  },
  {
    id: "005",
    name: "Pure Cotton Oversized T-shirt",
    company: "Stormborn",
    price: {
      current_price: 539,
      original_price: 999,
      off_price: "(46% OFF)",
    },
    rating: "4.5 ★ | 61",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/T-shirts.webp",
  },
  {
    id: "006",
    name: "Checked Blazer Dresses",
    company: "StyleCast",
    price: {
      current_price: 949,
      original_price: 2799,
      off_price: "(Rs.1850 OFF)",
    },
    rating: "3.5 ★ | 11",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/lady_dress.jpg",
  },
  {
    id: "007",
    name: "Men Slim Fit Blazer",
    company: "Jack & Jones",
    price: {
      current_price: 3299,
      original_price: 5999,
      off_price: "(45% OFF)",
    },
    rating: "3.3 ★ | 70",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/blazer.webp",
  },
  {
    id: "008",
    name: "Kids Cardigan Sweaters",
    company: "Little Angels",
    price: {
      current_price: 1399,
      original_price: 1999,
      off_price: "(30% OFF)",
    },
    rating: "4.5 ★ | 35",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/winter_wear.webp",
  },
  {
    id: "009",
    name: "Men Perforated Sneakers",
    company: "Red Tape",
    price: {
      current_price: 1799,
      original_price: 5999,
      off_price: "70% OFf",
    },
    rating: "4.3 ★ | 2.3k",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/sneaker.webp",
  },
  {
    id: "0010",
    name: "Men Metallic Straps Watch",
    company: "JOKER & WITCH",
    price: {
      current_price: 1494,
      original_price: 6499,
      off_price: "(77% OFF)",
    },
    rating: "4.2 ★ | 114",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/watch.webp",
  },
  {
    id: "0011",
    name: "Premium Men Polarise Sunglasses",
    company: "Carlton London",
    price: {
      current_price: 718,
      original_price: 1795,
      off_price: "(60% OFF)",
    },
    rating: "3.7 ★ | 49",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/glasses.webp",
  },
  {
    id: "0012",
    name: "Men 3 Fresh Active Deodorant",
    company: "Nivea",
    price: {
      current_price: 453,
      original_price: 855,
      off_price: "(47% OFF)",
    },
    rating: "4.2 ★ | 8.2k",
    return_date: "till 15 days after to delivered",
    delivery_date: "20 June 2024",
    warranty: "till 1 year after ordered",
    image: "images/nevea.webp",
  },
];
